package com.HallowKnight.Model;

public enum FixtureType {
    KNIGHT,
    KNIGHT_BOTTOM,
    KNIGHT_RIGHT,
    KNIGHT_LEFT,
    DEADLY,
    GROUND,
    PLATFORM,
    ENEMY,
    ENEMY_TOP,
    ENEMY_RIGHT,
    ENEMY_LEFT,
    ENEMY_BOTTOM,
    ENEMY_BOTTOM_LEFT,
    ENEMY_BOTTOM_RIGHT,
    ENEMY_RIGHT_RADAR,
    ENEMY_LEFT_RADAR,
    ENEMY_CIRCULAR_RADAR,
    LASER,
    NAIL,
    NPC,
    NPC_RADAR;
}
